belt_motor_61_controller:
    controller:
        package: dynamixel_controllers
        module: joint_torque_controller
        type: JointTorqueController
    joint_name: belt_motor_61
    joint_speed: 0.0
    motor:
        id: 61
        init: 0
        min: 0
        max: 0
