claw_motor_71_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: claw_motor_71
    joint_speed: 5.0
    motor:
        id: 71
        init: 0
        min: -10000
        max: 10000

claw_motor_72_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: claw_motor_72
    joint_speed: 5.0
    motor:
        id: 72
        init: 0
        min: -10000
        max: 10000

claw_motor_73_controller:
    controller:
        package: dynamixel_controllers
        module: joint_position_controller
        type: JointPositionController
    joint_name: claw_motor_73
    joint_speed: 5.0
    motor:
        id: 73
        init: 0
        min: -10000
        max: 10000